/**
 * Welcome Page (/)
 *
 * Displays latest Vestaboard content with voting functionality.
 * Fetches content from API and allows users to vote on quality.
 */

import { useState, useEffect, useCallback } from 'react';
import { PageLayout } from '../components/PageLayout';
import { VestaboardPreview } from '../components/VestaboardPreview';
import { VotingButtons } from '../components/VotingButtons';
import { apiClient } from '../services/apiClient';
import { textToCharacterCodes, emptyGrid } from '../lib/textToCharCodes';
import type { ContentRecord } from '../../../storage/models/content.js';

type VoteStatus = 'idle' | 'loading' | 'success' | 'error';

export function Welcome() {
  const [content, setContent] = useState<ContentRecord | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [voteStatus, setVoteStatus] = useState<VoteStatus>('idle');
  const [voteError, setVoteError] = useState<string | null>(null);

  const fetchContent = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await apiClient.getLatestContent();
      // Backend sends ContentRecord directly in data (not wrapped in { content: ... })
      if (response.data) {
        setContent(response.data);
      } else {
        setContent(null);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load content');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchContent();
  }, [fetchContent]);

  const handleVote = async (vote: 'good' | 'bad') => {
    if (!content) return;

    setVoteStatus('loading');
    setVoteError(null);

    try {
      await apiClient.submitVote({
        contentId: String(content.id),
        vote,
      });
      setVoteStatus('success');
      // Reset success state after 3 seconds
      setTimeout(() => setVoteStatus('idle'), 3000);
    } catch (err) {
      setVoteStatus('error');
      setVoteError(err instanceof Error ? err.message : 'Failed to submit vote');
    }
  };

  // Convert content text to character codes for display
  const characterCodes = content?.text ? textToCharacterCodes(content.text) : emptyGrid();

  // Loading state
  if (isLoading) {
    return (
      <PageLayout>
        <div className="max-w-5xl mx-auto">
          <h1 className="text-3xl font-bold text-center mb-8 text-gray-900 dark:text-white">
            Latest Content
          </h1>
          <div className="flex justify-center items-center py-16">
            <div className="text-gray-600 dark:text-gray-400">Loading content...</div>
          </div>
        </div>
      </PageLayout>
    );
  }

  // Error state
  if (error) {
    return (
      <PageLayout>
        <div className="max-w-5xl mx-auto">
          <h1 className="text-3xl font-bold text-center mb-8 text-gray-900 dark:text-white">
            Latest Content
          </h1>
          <div className="text-center py-16">
            <p className="text-red-600 dark:text-red-400 mb-4">{error}</p>
            <button
              onClick={fetchContent}
              className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
            >
              Try Again
            </button>
          </div>
        </div>
      </PageLayout>
    );
  }

  // Empty state
  if (!content) {
    return (
      <PageLayout>
        <div className="max-w-5xl mx-auto">
          <h1 className="text-3xl font-bold text-center mb-8 text-gray-900 dark:text-white">
            Latest Content
          </h1>
          <div className="text-center py-16">
            <VestaboardPreview content={emptyGrid()} className="mb-8 opacity-50" />
            <p className="text-gray-600 dark:text-gray-400">
              No content available yet. Generate some content to see it here!
            </p>
          </div>
        </div>
      </PageLayout>
    );
  }

  return (
    <PageLayout>
      <div className="max-w-5xl mx-auto">
        <h1 className="text-3xl font-bold text-center mb-8 text-gray-900 dark:text-white">
          Latest Content
        </h1>

        <VestaboardPreview content={characterCodes} className="mb-8" />

        <div className="text-center mb-6">
          <p className="text-sm text-gray-600 dark:text-gray-400">
            Generated by: <span className="font-semibold">{content.generatorId}</span>
          </p>
          <p className="text-xs text-gray-500 dark:text-gray-500">
            {new Date(content.generatedAt).toLocaleString()}
          </p>
        </div>

        <VotingButtons onVote={handleVote} isLoading={voteStatus === 'loading'} />

        {/* Vote feedback */}
        <div className="mt-4 text-center min-h-[24px]">
          {voteStatus === 'loading' && (
            <p className="text-gray-600 dark:text-gray-400">Submitting vote...</p>
          )}
          {voteStatus === 'success' && (
            <p className="text-green-600 dark:text-green-400">Thank you for your feedback!</p>
          )}
          {voteStatus === 'error' && <p className="text-red-600 dark:text-red-400">{voteError}</p>}
        </div>

        <div className="mt-4 text-center">
          <p className="text-sm text-gray-600 dark:text-gray-400">
            Help us improve! Vote on the quality of this content.
          </p>
        </div>
      </div>
    </PageLayout>
  );
}
