/**
 * Welcome Page (/)
 *
 * Displays Vestaboard preview with voting buttons
 */

import { PageLayout } from '../components/PageLayout';
import { VestaboardPreview } from '../components/VestaboardPreview';
import { VotingButtons } from '../components/VotingButtons';
import { getMockLatestContent, mockFormattedContent } from '../lib/mockData';

export function Welcome() {
  const latestContent = getMockLatestContent();

  const handleVote = (vote: 'good' | 'bad') => {
    // Placeholder - will connect to API later
    console.log(`Vote submitted: ${vote}`);
  };

  return (
    <PageLayout>
      <div className="max-w-5xl mx-auto">
        <h1 className="text-3xl font-bold text-center mb-8 text-gray-900 dark:text-white">
          Latest Content
        </h1>

        <VestaboardPreview content={mockFormattedContent} className="mb-8" />

        <div className="text-center mb-6">
          <p className="text-sm text-gray-600 dark:text-gray-400">
            Generated by: <span className="font-semibold">{latestContent.generatorId}</span>
          </p>
          <p className="text-xs text-gray-500 dark:text-gray-500">
            {new Date(latestContent.generatedAt).toLocaleString()}
          </p>
        </div>

        <VotingButtons onVote={handleVote} />

        <div className="mt-8 text-center">
          <p className="text-sm text-gray-600 dark:text-gray-400">
            Help us improve! Vote on the quality of this content.
          </p>
        </div>
      </div>
    </PageLayout>
  );
}
