# Docker Swarm Stack for Clack Track
# Deploy with: docker stack deploy -c stack.yml clack-track

version: '3.8'

services:
  app:
    image: clack-track:${IMAGE_TAG:-latest}
    networks:
      - clack-network
    ports:
      - '3030:3000'
    environment:
      # Non-sensitive config
      - NODE_ENV=production
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=clack_track
      - DATABASE_USER=root
      - WEB_SERVER_ENABLED=true
      - WEB_SERVER_PORT=3000
      - UPDATE_INTERVAL=${UPDATE_INTERVAL:-60}
      - TZ=${TZ:-America/Los_Angeles}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - WEATHER_ENTITY=${WEATHER_ENTITY:-weather.apple}
      - AI_PROVIDER=${AI_PROVIDER:-openai}
      # Tell app where to find secrets
      - SECRETS_PATH=/run/secrets
    secrets:
      - database_password_v1
      - vestaboard_api_key
      - vestaboard_api_url
      - openai_api_key
      - anthropic_api_key
      - home_assistant_url
      - home_assistant_token
      # VAPID secrets (optional - for push notifications)
      # Uncomment if you've generated VAPID keys with: npx web-push generate-vapid-keys
      # - vapid_public_key
      # - vapid_private_key
      # - vapid_subject
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "fetch('http://localhost:3000/').then(() => process.exit(0)).catch(() => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  mysql:
    image: mysql:8.0
    networks:
      - clack-network
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/database_password_v1
      - MYSQL_DATABASE=clack_track
    secrets:
      - database_password_v1
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  clack-network:
    driver: overlay

volumes:
  mysql_data:

# Secrets are created externally via secrets.sh
#
# SECRET VERSIONING PATTERN:
#   For zero-downtime secret rotation, use: ./secrets.sh rotate <secret_name>
#   This creates versioned secrets (e.g., database_password_v1, _v2) and updates
#   this file automatically. The old unversioned names below are the initial state.
#
#   Example rotation workflow:
#     1. Update secret value in .env.production
#     2. Run: ./secrets.sh rotate database_password
#     3. Script creates database_password_v1, updates this file, triggers service update
#     4. Optionally remove old secret when prompted
#
#   After rotation, entries below will show versioned names (e.g., database_password_v1)
#
secrets:
  database_password_v1:
    external: true
  vestaboard_api_key:
    external: true
  vestaboard_api_url:
    external: true
  openai_api_key:
    external: true
  anthropic_api_key:
    external: true
  home_assistant_url:
    external: true
  home_assistant_token:
    external: true
  # VAPID secrets (optional - uncomment if using push notifications)
  # vapid_public_key:
  #   external: true
  # vapid_private_key:
  #   external: true
  # vapid_subject:
  #   external: true
