import { Knex } from 'knex';

/**
 * Seed file for sample content data
 *
 * Provides realistic sample content for development and testing.
 * Includes variety of generator types, update types, and AI providers.
 */

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries (for clean, idempotent seeding)
  await knex('content').del();

  // Sample content with realistic Vestaboard text (6 rows × 22 chars)
  await knex('content').insert([
    {
      id: 1,
      text: 'THE ONLY WAY TO DO\nGREAT WORK IS TO\nLOVE WHAT YOU DO.\n- STEVE JOBS',
      type: 'major',
      generatedAt: new Date('2025-11-28T10:30:00Z'),
      sentAt: new Date('2025-11-28T10:30:05Z'),
      aiProvider: 'openai',
      aiModel: 'gpt-4.1-nano',
      modelTier: 'LIGHT',
      metadata: JSON.stringify({
        temperature: 0.7,
        maxTokens: 200,
        generationTime: 1250,
      }),
      status: 'success',
      generatorId: 'motivational-quote',
      generatorName: 'Motivational Quote Generator',
      priority: 2,
      failedOver: false,
      primaryProvider: null,
      primaryError: null,
      errorType: null,
      errorMessage: null,
      tokensUsed: 145,
    },
    {
      id: 2,
      text: 'WEATHER UPDATE\nSAN FRANCISCO\n72°F SUNNY\nWINDS 8 MPH NW\nHUMIDITY 45%',
      type: 'major',
      generatedAt: new Date('2025-11-28T14:00:00Z'),
      sentAt: new Date('2025-11-28T14:00:03Z'),
      aiProvider: 'anthropic',
      aiModel: 'claude-sonnet-4.5',
      modelTier: 'MEDIUM',
      metadata: JSON.stringify({
        temperature: 0.5,
        maxTokens: 300,
        generationTime: 1800,
        location: 'San Francisco, CA',
      }),
      status: 'success',
      generatorId: 'weather-focus',
      generatorName: 'Weather Focus Generator',
      priority: 2,
      failedOver: false,
      primaryProvider: null,
      primaryError: null,
      errorType: null,
      errorMessage: null,
      tokensUsed: 220,
    },
    {
      id: 3,
      text: 'BREAKING NEWS\nTECH STOCKS RALLY\n+2.3% ON NASDAQ\nAI SECTOR LEADS\nGAINS',
      type: 'major',
      generatedAt: new Date('2025-11-28T16:45:00Z'),
      sentAt: new Date('2025-11-28T16:45:04Z'),
      aiProvider: 'openai',
      aiModel: 'gpt-4.1-mini',
      modelTier: 'MEDIUM',
      metadata: JSON.stringify({
        temperature: 0.6,
        maxTokens: 250,
        generationTime: 1600,
        sources: ['Reuters', 'Bloomberg'],
      }),
      status: 'success',
      generatorId: 'news-summary',
      generatorName: 'News Summary Generator',
      priority: 2,
      failedOver: false,
      primaryProvider: null,
      primaryError: null,
      errorType: null,
      errorMessage: null,
      tokensUsed: 185,
    },
    {
      id: 4,
      text: 'FRONT DOOR OPENED\nWELCOME HOME!\n3:24 PM',
      type: 'major',
      generatedAt: new Date('2025-11-28T15:24:00Z'),
      sentAt: new Date('2025-11-28T15:24:01Z'),
      aiProvider: 'openai',
      aiModel: 'gpt-4.1-nano',
      modelTier: 'LIGHT',
      metadata: JSON.stringify({
        eventType: 'state_changed',
        entityId: 'binary_sensor.front_door',
        eventPattern: 'door_opened',
      }),
      status: 'success',
      generatorId: 'door-notification',
      generatorName: 'Door Notification Generator',
      priority: 0,
      failedOver: false,
      primaryProvider: null,
      primaryError: null,
      errorType: null,
      errorMessage: null,
      tokensUsed: 45,
    },
    {
      id: 5,
      text: 'SYSTEM ERROR\nFAILED TO GENERATE\nCONTENT\nUSING FALLBACK',
      type: 'major',
      generatedAt: new Date('2025-11-28T18:00:00Z'),
      sentAt: new Date('2025-11-28T18:00:02Z'),
      aiProvider: 'fallback',
      aiModel: null,
      modelTier: null,
      metadata: JSON.stringify({
        fallbackReason: 'rate_limit_exceeded',
        attemptedProviders: ['openai', 'anthropic'],
      }),
      status: 'failed',
      generatorId: 'static-fallback',
      generatorName: 'Static Fallback Generator',
      priority: 3,
      failedOver: true,
      primaryProvider: 'openai',
      primaryError: 'Rate limit exceeded - too many requests',
      errorType: 'RateLimitError',
      errorMessage: 'All AI providers exhausted, using fallback content',
      tokensUsed: 0,
    },
    {
      id: 6,
      text: '12:00 PM\nSAN FRANCISCO\n72°F SUNNY',
      type: 'minor',
      generatedAt: new Date('2025-11-28T12:00:00Z'),
      sentAt: new Date('2025-11-28T12:00:02Z'),
      aiProvider: 'programmatic',
      aiModel: null,
      modelTier: null,
      metadata: JSON.stringify({
        updateType: 'minor',
        cachedContentId: 2,
        frameOnly: true,
      }),
      status: 'success',
      generatorId: 'minor-update',
      generatorName: 'Minor Update Generator',
      priority: 1,
      failedOver: false,
      primaryProvider: null,
      primaryError: null,
      errorType: null,
      errorMessage: null,
      tokensUsed: 0,
    },
  ]);
}
